version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seafood_bot
    restart: always
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"